'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("randomLogWriter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Log_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Log_Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2
        '''1080
        '''&amp;c
        '''10-point
        '''10th
        '''11-point
        '''12-point
        '''16-point
        '''18-point
        '''1st
        '''2,4,5-t
        '''2,4-d
        '''20-point
        '''2D
        '''2nd
        '''30-30
        '''3D
        '''3-D
        '''3M
        '''3rd
        '''48-point
        '''4-D
        '''4GL
        '''4H
        '''4th
        '''5-point
        '''5-T
        '''5th
        '''6-point
        '''6th
        '''7-point
        '''7th
        '''8-point
        '''8th
        '''9-point
        '''9th
        '''a
        '''a&apos;
        '''a-
        '''A&amp;M
        '''A&amp;P
        '''A.
        '''A.A.A.
        '''A.B.
        '''A.B.A.
        '''A.C.
        '''A.D.
        '''A.D.C.
        '''A.F.
        '''A.F.A.M.
        '''A.G.
        '''A.H.
        '''A.I.
        '''A.I.A.
        '''A.I.D.
        '''A.L.
        '''A.L.P.
        '''A.M.
        '''A.M.A.
        '''A.M.D.G.
        '''A.N.
        '''a.p.
        '''a.r.
        '''A.R.C.S.
        '''A.U.
        '''A.U.C.
        '''A.V.
        '''a.w.
        '''A.W.O.L.
        '''A/C
        '''A/F
        '''A/O
        '''A/P
        '''A/V
        '''A1
        '''A-1
        '''A4
        '''A5
        '''AA
        '''AAA
        '''AAAA
        '''AAAAAA
        '''AAAL
        '''AAAS
        '''Aaberg
        '''Aachen
        '''AAE
        '''AAEE
        '''AAF
        '''AAG
        '''aah
        '''aahed
        '''aahing
        '''aahs
        '''AAII
        '''aal
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property words() As String
            Get
                Return ResourceManager.GetString("words", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
